name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        
      - name: Install main packages
        run: yarn
  
      - name: Install Cloudflare worker packages
        run: npm install
        working-directory: ./workers-site

      - name: Configure
        run: sed -i s\|data-version=\"v1.0.0.0\"\|data-version=\"$(date '+%y.%m.%d').$GITHUB_RUN_NUMBER\"\|g public/index.html
  
      - name: Build
        run: yarn build
  
      - name: Deploy to Cloudflare (dev)
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
        run: yarn wrangler publish -e dev
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  
      - name: Deploy to Cloudflare (prod)
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/prod' }}
        run: yarn wrangler publish -e prod
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
