name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        
      - name: Install Cloudflare Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Install packages
        run: yarn
  
      - name: Build
        run: yarn build
  
      - name: Deploy to Cloudflare (dev)
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
        run: wrangler publish -e dev
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  
      - name: Deploy to Cloudflare (prod)
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/prod' }}
        run: wrangler publish -e prod
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
